### ISSUE TITLE
UI Enhancements

### ISSUE THREAD

**Issue by isultania** [uno-isqa-8950/fitgirl-inc#100]

**Comment by isultania** [comment]
Create Tasks and assign to whoever you want to.

**Comment by harsh1930** [comment]
Working on it.

**Comment by harsh1930** [comment]
Sorry this was done by mistake.

**Comment by isultania** [comment]
In Mobile Mode:  login Page, Top bar is blue, and Empoweru Logo should be used.

**Comment by isultania** [comment]
In mobile mode: Logout page, the div is too small.  You have to scroll up even if content is too les...

**Comment by isultania** [comment]
Pending from a long time.
