### ISSUE TITLE
Create Pages Tab needs to be removed

### ISSUE THREAD

**Issue by adoll04** [uno-isqa-8950/fitgirl-inc#135]
![image.png](https://images.zenhubusercontent.com/5b85d9d57749fb151f068bca/d28511fe-e2c3-43ae-8a43-0daa9f7c0b10)

Click on Preview tab

**Comment by vnikesh** [comment]
![no_create_program](https://user-images.githubusercontent.com/29901810/46638322-fe91da00-cb25-11e8-9d60-3af18ec41ff4.PNG)
No Create Program Tab for Admin

**Comment by vnikesh** [comment]
Reopening the issues because of the code uploaded on Sprint2-Dummy is not available in Masters. Have to add these changes to Master from Sprint2-Dummy
