### ISSUE TITLE
User Table

### ISSUE THREAD

**Issue by adoll04** [uno-isqa-8950/fitgirl-inc#137]
Color should be Black, White, Pink or Gray

Not blue

**Comment by vnikesh** [comment]
![pink color for user tab](https://user-images.githubusercontent.com/29901810/46638409-5f211700-cb26-11e8-9811-14e6e0890342.PNG)
Color of the tab changed to Pink

**Comment by vnikesh** [comment]
Reopening the issues because of the code uploaded on Sprint2-Dummy is not available in Masters. Have to add these changes to Master from Sprint2-Dummy

**Comment by harsh1930** [comment]
This is fine now.
