### ISSUE TITLE
All Programs

### ISSUE THREAD

**Issue by adoll04** [uno-isqa-8950/fitgirl-inc#141]
![image.png](https://images.zenhubusercontent.com/5b85d9d57749fb151f068bca/7ba44f9e-a634-42da-8c56-6b9c07828ac5)

Color should not be green. 
Pink, black, white, or gray

**Comment by vnikesh** [comment]
![progra_tab_color](https://user-images.githubusercontent.com/29901810/46638475-a8716680-cb26-11e8-8692-61009688fd4d.PNG)
Now the color is in black and grey

**Comment by vnikesh** [comment]
Reopening the issues because of the code uploaded on Sprint2-Dummy is not available in Masters. Have to add these changes to Master from Sprint2-Dummy

**Comment by vnikesh** [comment]
Closing the issue because we sticking to the old UI
