### ISSUE TITLE
Admin - Link User Tab on Nav bar to User page

### ISSUE THREAD

**Issue by vnikesh** [uno-isqa-8950/fitgirl-inc#146]
User Tab from Navbar has to be linked to the User.

**Comment by vnikesh** [comment]
User tab on the navbar is showing user when clicked on the tab

**Comment by vnikesh** [comment]
Reopening the issues because of the code uploaded on Sprint2-Dummy is not available in Masters. Have to add these changes to Master from Sprint2-Dummy

**Comment by isultania** [comment]
who did this ?
