### ISSUE TITLE
Change Password- User Dashboard

### ISSUE THREAD

**Issue by isultania** [uno-isqa-8950/fitgirl-inc#162]
Password Suggestion should be in tool tip
![image.png](https://images.zenhubusercontent.com/5b85d9bd7749fb151f068bc9/cda58a16-f39e-4d3e-a6cd-db5c4f726445)

**Comment by isultania** [comment]
Is this done ?
I can still see
![image](https://user-images.githubusercontent.com/29930127/47382400-dc708e00-d6c7-11e8-9edb-ebd94a39e295.png)

**Comment by anilpg1** [comment]
It is done on my local machine. Looks like when I pushed to git few days
aga, it didn't upload all the changes that I did. I spoke with Harsh he has
updated the Master. I will look later to see if it is working. But it done
though

On Tue, Oct 23, 2018 at 1:33 PM Ishma Sultania <notifications@github.com>
wrote:

> Is this done ?
> I can still see
> [image: image]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_29930127_47382400-2Ddc708e00-2Dd6c7-2D11e8-2D9edb-2Debd94a39e295.png&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=fhYCpXssPvVdIvSOIh74vPRIpXlxNB34gGGICDqINeM&m=NnXRjFYcctPIR2SkYt0nAZdcLlJXC9dz22E46SUT5mQ&s=hW9RlNFwQ6wOivLGs5891jC3mWuuGW5dTEY3afVX9kI&e=>
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uno-2Disqa-2D8950_fitgirl-2Dinc_issues_162-23issuecomment-2D432366545&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=fhYCpXssPvVdIvSOIh74vPRIpXlxNB34gGGICDqINeM&m=NnXRjFYcctPIR2SkYt0nAZdcLlJXC9dz22E46SUT5mQ&s=LwaWE8ia5b6JHBtSr5XSH2R7bdiMlTsnEj1uERTg-yU&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AiO-5Fjwo6iT5AY7t1IPrgm0oe-5FHLPpZTfks5un2D1gaJpZM4Xtue2&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=fhYCpXssPvVdIvSOIh74vPRIpXlxNB34gGGICDqINeM&m=NnXRjFYcctPIR2SkYt0nAZdcLlJXC9dz22E46SUT5mQ&s=qAAElsARlk7Plo36o5bIB_fzXMRPtwguBVGB9unXntw&e=>
> .
>


-- 
Anil Papugani M.S.
Information Systems and Quantitative Analysis
Management Information Systems
1110 S.67th Street
University of Nebraska - Omaha
Omaha, NE - 68182-0392

**Comment by abbubhai** [comment]
This is done
