### ISSUE TITLE
Rewards Redemption

### ISSUE THREAD

**Issue by adoll04** [uno-isqa-8950/fitgirl-inc#255]
From Cheri - I think you get an email which is probably how we need to set up our reward system so if they click on what they want then it automatically shoots a picture of reward and what they get to their email account that way they can print it and take it to the store. It will need to have I’m sure a FITGIRL logo on it

**Comment by bvanscoy678** [comment]
@jlofshultuno  For now, I assigned to you as we collect more information of her needs, we can pass itto the correct lead.

**Comment by bvanscoy678** [comment]
I merged with #369
