### ISSUE TITLE
As a system, I want to display the weeks in chronological order. 

### ISSUE THREAD

**Issue by FitGirl-Omaha** [uno-isqa-8950/fitgirl-inc#312]
For the program users the weeks are not displayed in the proper order. See screenshot below

![image](https://user-images.githubusercontent.com/46053467/50353107-cc7cfb00-050c-11e9-8d4d-28d687f35b4a.png)

**Comment by jlofshultuno** [comment]
Need to verify. Test case - enter weeks out of order in content management site and then display on user site.

**Comment by bvanscoy678** [comment]
I think this issue is resolved (it appears correct in production). Ishma showed the class how to move pages with Wagtail.
