### ISSUE TITLE
Setup AWS S3 configuration with FitGirl-Omaha EmpowerU account

### ISSUE THREAD

**Issue by SachinPawaskarUNO** [uno-isqa-8950/fitgirl-inc#314]
Setup AWS S3 configuration with @FitGirl-Omaha EmpowerU account. Account needs to be created by @FitGirl-Omaha first and then app must be configured to store images, pdfs and uploads from EmpowerU CMS system.

**Comment by jlofshultuno** [comment]
@isultania Is S3 still the desired repository? Is this still a relevant issue?

**Comment by khd20** [comment]
Impediment: Cannot migrate media files
