### ISSUE TITLE
Extras Page - needs to be re-worded

### ISSUE THREAD

**Issue by FitGirl-Omaha** [uno-isqa-8950/fitgirl-inc#315]
Click on these sites and apps to learn, grow into that strong, confident, kind, unstoppable girl you know you are capable of becoming!

https://www.amightygirl.com/

https://girlyouare.com/

Know More about FitGirl, Inc.:
FITGirl Inc. Website

**Comment by karthikBellaryVijaya** [comment]
@ Hema - The content seems to be consistent. Kindly check for verbiage on the extras page and let me know if you see something amiss. The only content that needs to be removed is the heading "Extras!" and "Learn more!". Kindly confirm if we need to remove that text.

[image](https://user-images.githubusercontent.com/31267526/51208418-3e115480-18d3-11e9-9456-f423a14c2838.png)
