### ISSUE TITLE
Consistent centering and text size: About Us

### ISSUE THREAD

**Issue by FitGirl-Omaha** [uno-isqa-8950/fitgirl-inc#318]
Text not centered and seems small 
FOOD, FUN, FITNESS & FRIENDS!
Being active not only makes you feel good about yourself, it makes you healthier. Our goal at FITGirl, Inc is to introduce you to fun physical activities and help you discover the strong, confident, brave person you were created to be by sharing ideas and tips that will help you:

Deal with Difficult Feelings

Stop Bullying

Learn How to Say No to Peer Pressure

Choose Healthy Food Options

Make New Friends

Give Back to the Community

Control Fear & Anxiety

Stay Active 60 Minutes a Day

Change Negative Self Talk

Learn to Love Your Body

Become Confident in Everything you Do!

The mission of FITGirl, Inc is to empower young girls as they develop and mature by demonstrating positive lifestyle choices: mental, physical, relational and nutritional.

**Comment by jlofshultuno** [comment]
Need to connect to CMS
