### ISSUE TITLE
Email - Group 

### ISSUE THREAD

**Issue by bvanscoy678** [uno-isqa-8950/fitgirl-inc#341]
Cheri would like to be able to send out mass emails and also individual emails.

**Comment by bvanscoy678** [comment]
The issue passed the functional test, but holding off on closing until Hema can discuss the design with the group.

**Comment by bvanscoy678** [comment]
Hema added additional functionality be adding checkboxes. In testing, I noticed it only selects the active page and not subsequent pages. Holding off on closing until the issue is resolved.

**Comment by karthikBellaryVijaya** [comment]
This a duplicate issue(based on changes suggested by Cheri and Dr P)
