### ISSUE TITLE
Add affirmation popups

### ISSUE THREAD

**Issue by bvanscoy678** [uno-isqa-8950/fitgirl-inc#367]

**Comment by isultania** [comment]
This won't be part of Beta Launch

**Comment by jlofshultuno** [comment]
Content has been provided. Affirmations should pop up the first time a user logs in each day. Affirmation content is based on the week that is active

**Comment by bvanscoy678** [comment]
@isultania . It is out understanding that this is a big priority for the client.

**Comment by bvanscoy678** [comment]
From @jlofshultuno . Each day users should receive a pop-up with an affirmation associated with that week when they log in the first time that day - Cheri provided the content - Monday the popup should be about the theme of the week. Each day after that is a related affirmation
