### ISSUE TITLE
Define rewards redemption process

### ISSUE THREAD

**Issue by bvanscoy678** [uno-isqa-8950/fitgirl-inc#369]

**Comment by bvanscoy678** [comment]
From merged task #255. : From Cheri - I think you get an email which is probably how we need to set up our reward system so if they click on what they want then it automatically shoots a picture of reward and what they get to their email account that way they can print it and take it to the store. It will need to have I’m sure a FITGIRL logo on it

**Comment by jlofshultuno** [comment]
At the end of week 12, once a user has completed the post-assessment, they will be directed to the rewards page where they can redeem their points.  When a user clicks on a rewards category (e.g. 100 points), the rewards that are no longer available will be grayed out. The user will click on the available reward, and confirm the redemption. This will create an email to Cheri and the user confirming the redemption. The users available points will also immediately be debited by the amount redeemed. The user will take the email to FitGirl to pick up their gift card.

**Comment by shamrose** [comment]
Our team discussed the mockups and demonstrated the mockups in Sprint-2
