### ISSUE TITLE
As an administrator, I want to be able to track if a reward has already been redeemed.

### ISSUE THREAD

**Issue by jlofshultuno** [uno-isqa-8950/fitgirl-inc#376]

**Comment by bvanscoy678** [comment]
@hcghanta. Not sure how to test this issue since it will be part of this script too.

**Comment by hcghanta** [comment]
This is the yes and no redeem status buttons on Manage Points tab on Admin side

**Comment by bvanscoy678** [comment]
Works As expected. I assigned 3 points, please let me know if different.
