### ISSUE TITLE
Pre/post assessment, UI, Date and Date/Time field doesn’t have format specified

### ISSUE THREAD

**Issue by bvanscoy678** [uno-isqa-8950/fitgirl-inc#380]
Pre/post assessment, UI, Date and Date/Time field doesn’t have format specified. Fix: add a placeholder (enter in mm/dd/yyyy format)![preassesment.JPG](https://images.zenhubusercontent.com/5c3512956cefdb13ee7f759a/d8c20b2c-561d-4cb5-b4a7-d77dbde24a95)

**Comment by isultania** [comment]
This is what you added as content. You can frame any question from it. This
seems to be irrelevant to me.

**Comment by khd20** [comment]
Add a validation error on html page 
Research backend functionality from wagtail 

Issue - straight form from the model + need to create a form in wagtail (Joe's recommendation)

**Comment by hcghanta** [comment]
Not an issue.
