### ISSUE TITLE
Profile Name - Out of slot

### ISSUE THREAD

**Issue by bvanscoy678** [uno-isqa-8950/fitgirl-inc#383]
Mobile UI, for All Users page . ![Profile name.JPG](https://images.zenhubusercontent.com/5c3512956cefdb13ee7f759a/647c527f-3e6c-4e48-bda6-3749ab3919b6)Profile name goes out of slot

**Comment by isultania** [comment]
Is this done ?

**Comment by hcghanta** [comment]
We eventually figured that this is not an issue. The UI is now good without
doing any changes. So this has to be deleted. Since we couldn’t do that
Brent moved it to done.

**Comment by isultania** [comment]
I don't think closing issue is a good idea. Issues should be closed only if
it is resolved. You can always make another pipeline.
