### ISSUE TITLE
Question Page - Checkbox choice doesn’t show

### ISSUE THREAD

**Issue by bvanscoy678** [uno-isqa-8950/fitgirl-inc#384]
![question does not show.JPG](https://images.zenhubusercontent.com/5c3512956cefdb13ee7f759a/d8cd02ee-ebad-42b3-852a-20079ae0f4ff)

**Comment by bvanscoy678** [comment]
![image.png](https://images.zenhubusercontent.com/5c3512956cefdb13ee7f759a/de11b233-8ec8-474a-9ab4-1a6c078c6c2f)

**Comment by isultania** [comment]
It this Question Page or Question Page Text?

**Comment by bvanscoy678** [comment]
@isultania . Does this  help?
![image](https://user-images.githubusercontent.com/7416828/51324223-c99ff800-1a2f-11e9-8be0-50ac432b674d.png)
![image](https://user-images.githubusercontent.com/7416828/51324243-d58bba00-1a2f-11e9-8c1b-673abe53764b.png)

**Comment by aishwaryamsd** [comment]
Hi, 
Hemachandra told me it is question text page

**Comment by hcghanta** [comment]
**Deleted @aishwaryamsd @bvanscoy678 comments to avoid confusion.
Not just in question/question text page, there is option to include check box field in post and pre-assessment as well. When you select checkbox field and enter choices it doesn't show up on the user side.
However I just noticed that it is mentioned "choices are applicable for checkboxes" but not for checkbox (you can see that in the screenshot). So @bvanscoy678 you can actually delete this task!

**Comment by bvanscoy678** [comment]
@hcghanta I will close. Thanks
