### ISSUE TITLE
Questions Page text - Home page button error?

### ISSUE THREAD

**Issue by bvanscoy678** [uno-isqa-8950/fitgirl-inc#385]
Question page text, Functionality, After submitting question page text it takes back to the same question page saying the question is submitted instead it should be taking to Home page. This works perfectly for physical page after completion of timer
![image.png](https://images.zenhubusercontent.com/5c3512956cefdb13ee7f759a/0e4197ed-c46e-4269-a539-1fa6f4ed9738)
![image.png](https://images.zenhubusercontent.com/5c3512956cefdb13ee7f759a/17893572-6915-4077-9613-6f58b90592c1)

**Comment by isultania** [comment]
This needs to be fixed on priority
