### ISSUE TITLE
Mental Page - PDF Download

### ISSUE THREAD

**Issue by bvanscoy678** [uno-isqa-8950/fitgirl-inc#386]
Art page in mental page module has PDF that downloads on click so better call it "download" than print. This is related to another issue that has been raised (issue #340)
![image.png](https://images.zenhubusercontent.com/5c3512956cefdb13ee7f759a/766dabb2-b3e2-42bc-88e6-bc263efe1586)

**Comment by isultania** [comment]
This was according to client requirement. Reconfirm with Client

**Comment by hcghanta** [comment]
Add documents in Prod

**Comment by miskelley** [comment]
This is not a coding issue. This is a content issue. I updated the text in CMS on each of these pages for week 5. I'm going to ask Kent if he can go through the rest of the program and update in CMS.
