### ISSUE TITLE
Confirm Each Week is a Theme - Content

### ISSUE THREAD

**Issue by bvanscoy678** [uno-isqa-8950/fitgirl-inc#397]
We need to make sure each week's theme is consistent across the week's content. @jlofshultuno will follow up with client to confirm the theme's.  Then team members will work on making this happen.

**Comment by bvanscoy678** [comment]
This tasks is tied to #346 & #392. i

**Comment by jlofshultuno** [comment]
The only theme related content is affirmations and bonus content. Cheri is working on bonus content
