### ISSUE TITLE
Footer Issue - Question Page Text

### ISSUE THREAD

**Issue by bvanscoy678** [uno-isqa-8950/fitgirl-inc#423]
If you already answered a question page text and you try to access it the message is correct but the footer is messed up
![image.png](https://images.zenhubusercontent.com/5c3512956cefdb13ee7f759a/9d54543e-b3af-4ba6-a8ec-339c91f24024)

**Comment by bvanscoy678** [comment]
Please check to see if this is across all pages.

**Comment by bvanscoy678** [comment]
From @hcghanta   I did not see it on other pages. Also when you first visit the question text page it’s fine, once you answer the question and revisit the page then this UI error

**Comment by aishwaryamsd** [comment]
This issue is fixed.
