### ISSUE TITLE
Challenge Question Page - Submit and Return buttons don't line to the left

### ISSUE THREAD

**Issue by bvanscoy678** [uno-isqa-8950/fitgirl-inc#426]
![image.png](https://images.zenhubusercontent.com/5c3512956cefdb13ee7f759a/710fb54d-e44e-440c-bf8c-bd5c85805146)

**Comment by bvanscoy678** [comment]
Same thing on the bonus question quiz.

**Comment by hcghanta** [comment]
This alignment issue is on question page, question page text and print page

**Comment by bvanscoy678** [comment]
I also see issues here: http://www.empoweruomaha.com/pages/spring-2019/week-10/mental/self-esteem/recipe-making-great-friends

 and here:  http://www.empoweruomaha.com/pages/spring-2019/week-6/nutritional/trail-mix/challenges/

**Comment by hcghanta** [comment]
> I also see issues here: http://www.empoweruomaha.com/pages/spring-2019/week-10/mental/self-esteem/recipe-making-great-friends -> **This is a question page text**
> 
> and here: http://www.empoweruomaha.com/pages/spring-2019/week-6/nutritional/trail-mix/challenges/ -> **This is a question page**
