### ISSUE TITLE
Create Student Users in Production

### ISSUE THREAD

**Issue by bvanscoy678** [uno-isqa-8950/fitgirl-inc#437]
@cecelia0128 . Please check with Shamrose on the details to create the users we dicussed in class.

**Comment by cecelia0128** [comment]
@bvanscoy678 I talked to @shamrose  yesterday, he says that client will be uploading the actual fitgirl account herself instead of us uploading the dummy one, so this can be put on hold.

**Comment by bvanscoy678** [comment]
@cecelia0128 . Okay.
