### ISSUE TITLE
embedding interactive coloring pages 

### ISSUE THREAD

**Issue by jlofshultuno** [uno-isqa-8950/fitgirl-inc#446]

**Comment by miskelley** [comment]
Need to make it responsive and attribute it to the source.

**Comment by hcghanta** [comment]
working on running unsafe scripts on

**Comment by bvanscoy678** [comment]
@miskelley reported issues using the app on an actual iphone. More testing and a solution is in the works.

**Comment by karthikBellaryVijaya** [comment]
Needs to be checked in iPad and Iphone.

**Comment by bvanscoy678** [comment]
@karthikBellaryVijaya . I tested on an iPhone 6plus and the app does not show up.  The header and description shows, but not the coloring app.

**Comment by shamrose** [comment]
Brent,did you check the coloring app on production application or dev,
because I had fixed this in dev.

On Mon, Mar 4, 2019 at 9:36 AM Brent Van Scoy <notifications@github.com>
wrote:

> @karthikBellaryVijaya
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_karthikBellaryVijaya&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=P-dTN0soHkA2ipfN7I-A1mQYLKJ59BnQ2vLk8s5_BYQ&m=qbC-YEMT2xT3meMG5bLimk6X93feA5C0AvPayAFZb4k&s=IV9hnXzcvZI-2v2ifExU7dtsVhuC3AN171OWJa_M2po&e=>
> . I tested on an iPhone 6plus and the app does not show up. The header and
> description shows, but not the coloring app.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uno-2Disqa-2D8950_fitgirl-2Dinc_issues_446-23issuecomment-2D469297103&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=P-dTN0soHkA2ipfN7I-A1mQYLKJ59BnQ2vLk8s5_BYQ&m=qbC-YEMT2xT3meMG5bLimk6X93feA5C0AvPayAFZb4k&s=ikHrqF9sODJvaMucfIqgu2U-QegHpDvH14tSlZ5VT9g&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ad0JFKkCTPGeeO8G8bIM2fiAky-2Ds-5Ftczks5vTT1hgaJpZM4aUSuE&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=P-dTN0soHkA2ipfN7I-A1mQYLKJ59BnQ2vLk8s5_BYQ&m=qbC-YEMT2xT3meMG5bLimk6X93feA5C0AvPayAFZb4k&s=3Ih46SsD6M5i4SSkRNdDAE_EmfE-ttB8fFwxuA83y7A&e=>
> .
>
-- 
Sincerely,
Shamrose Makandar,
Graduate Assistant-Management Information Systems,
College of Information Science & Technology,
The University of Nebraska at Omaha,
Email: smakandar@unomaha.edu
Mobile: (737)202-5219

**Comment by bvanscoy678** [comment]
@shamrose. I checked on Prod. Let me see if I can clear the cache on the phone

**Comment by shamrose** [comment]
Can you Check it on dev because I have fixed it on dev and haven’t pushed
those changes to prod app

On Mon, Mar 4, 2019 at 9:47 AM Brent Van Scoy <notifications@github.com>
wrote:

> @shamrose
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_shamrose&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=P-dTN0soHkA2ipfN7I-A1mQYLKJ59BnQ2vLk8s5_BYQ&m=bmMZlo8juuIlSibdHQQCxjuxoIkwxtzlyuaqNrIvAvo&s=tWQ5sduuYkrmb91_27j8ZFBqElqVBBW-KEtzrWnND5I&e=>.
> I checked on Prod. Let me see if I can clear the cache on the phone
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uno-2Disqa-2D8950_fitgirl-2Dinc_issues_446-23issuecomment-2D469301402&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=P-dTN0soHkA2ipfN7I-A1mQYLKJ59BnQ2vLk8s5_BYQ&m=bmMZlo8juuIlSibdHQQCxjuxoIkwxtzlyuaqNrIvAvo&s=eNTLQjHhq_3j-uzd-65X00XiP0bpu9YSVSX86FuK1Qk&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ad0JFEHmA3MyGzQw28HbvIydwqCT07Wtks5vTT-5F3gaJpZM4aUSuE&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=P-dTN0soHkA2ipfN7I-A1mQYLKJ59BnQ2vLk8s5_BYQ&m=bmMZlo8juuIlSibdHQQCxjuxoIkwxtzlyuaqNrIvAvo&s=CjXCbuceLwXy0-Ifx8C6kAOZ0RBue0sFwm6RCSWUBFg&e=>
> .
>
-- 
Sincerely,
Shamrose Makandar,
Graduate Assistant-Management Information Systems,
College of Information Science & Technology,
The University of Nebraska at Omaha,
Email: smakandar@unomaha.edu
Mobile: (737)202-5219

**Comment by bvanscoy678** [comment]
@shamrose . I am in Week 5 in DEV and I don't see the app.

**Comment by shamrose** [comment]
Okay, I have added the coloring app on dev in week 5

On Mon, Mar 4, 2019 at 9:51 AM Brent Van Scoy <notifications@github.com>
wrote:

> @shamrose
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_shamrose&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=P-dTN0soHkA2ipfN7I-A1mQYLKJ59BnQ2vLk8s5_BYQ&m=1Teu6IEmf0bFzTsyJJ25uXROmHYwJyAzNuqqZmi9W74&s=rSnTKy5pyeL4YnRSEphZTgrZFrJFfh01wpZDjkvEPtQ&e=>
> . I am in Week 5 in DEV and I don't see the app.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uno-2Disqa-2D8950_fitgirl-2Dinc_issues_446-23issuecomment-2D469303192&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=P-dTN0soHkA2ipfN7I-A1mQYLKJ59BnQ2vLk8s5_BYQ&m=1Teu6IEmf0bFzTsyJJ25uXROmHYwJyAzNuqqZmi9W74&s=IdAp9EYEYa0tBl6weVgZs9djo5oBUFOVcj857TK1lGE&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ad0JFIcT-2DISqKpNWuzU4pm32Wv44KNYMks5vTUEMgaJpZM4aUSuE&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=P-dTN0soHkA2ipfN7I-A1mQYLKJ59BnQ2vLk8s5_BYQ&m=1Teu6IEmf0bFzTsyJJ25uXROmHYwJyAzNuqqZmi9W74&s=rpnsy0Ve-OyEWrxt3hQ1h9PUdGfNbS35wHi1z-LV7Xw&e=>
> .
>
-- 
Sincerely,
Shamrose Makandar,
Graduate Assistant-Management Information Systems,
College of Information Science & Technology,
The University of Nebraska at Omaha,
Email: smakandar@unomaha.edu
Mobile: (737)202-5219

**Comment by bvanscoy678** [comment]
I can see in DEV, but nothing happens when I click on the image. 
![image](https://user-images.githubusercontent.com/7416828/53745231-3a766480-3e64-11e9-9040-8505f536517c.png)

**Comment by shamrose** [comment]
Yes I saw that in my iPad as well, probably we need to fix it in the html
styling, on the laptop and desktop it looks fine though.

On Mon, Mar 4, 2019 at 9:59 AM Brent Van Scoy <notifications@github.com>
wrote:

> I can see in DEV, but nothing happens when I click on the image.
> [image: image]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_7416828_53745231-2D3a766480-2D3e64-2D11e9-2D9040-2D8505f536517c.png&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=P-dTN0soHkA2ipfN7I-A1mQYLKJ59BnQ2vLk8s5_BYQ&m=QqLS_Ud3Ph4TGIcXOiY-YkrBmVMqFKIZlKb1iOPwT1w&s=hmIO2f-UNozZlIBGDGRwu03iLBJK-uxUD5dO-9NDEgk&e=>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uno-2Disqa-2D8950_fitgirl-2Dinc_issues_446-23issuecomment-2D469306444&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=P-dTN0soHkA2ipfN7I-A1mQYLKJ59BnQ2vLk8s5_BYQ&m=QqLS_Ud3Ph4TGIcXOiY-YkrBmVMqFKIZlKb1iOPwT1w&s=L7BnSena3bdU4fvOeQajDwHz3oChZi9QY8PDXXl-ZOs&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ad0JFN8p4ou0cMoJuBKiKpxRM9yK-5FHWMks5vTULxgaJpZM4aUSuE&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=P-dTN0soHkA2ipfN7I-A1mQYLKJ59BnQ2vLk8s5_BYQ&m=QqLS_Ud3Ph4TGIcXOiY-YkrBmVMqFKIZlKb1iOPwT1w&s=NPTxqUCyJ5sjthbnJrtSPGodIYVyrh-pF2E96N4RbLo&e=>
> .
>
-- 
Sincerely,
Shamrose Makandar,
Graduate Assistant-Management Information Systems,
College of Information Science & Technology,
The University of Nebraska at Omaha,
Email: smakandar@unomaha.edu
Mobile: (737)202-5219

**Comment by bvanscoy678** [comment]
The app is still not working on an iPhone or iPad. Failed testing.

**Comment by bvanscoy678** [comment]
Failed testing in the mobile environment

**Comment by jlofshultuno** [comment]
Change to just displaying a link if on an iPad or iPhone
