### ISSUE TITLE
As a user, I want the change password confirmation (error) message to say "Confirmation passwords do not match"

### ISSUE THREAD

**Issue by bvanscoy678** [uno-isqa-8950/fitgirl-inc#462]

**Comment by khd20** [comment]
Impediment: Error given by Django cannot be change easily 
Recommendation by Ishma: Do from it from front end, jquery, or javascript

**Comment by shamrose** [comment]
@karthikBellaryVijaya suggests to trying to do this through DJango

**Comment by srishtynayak** [comment]
not required
