### ISSUE TITLE
QA - Hyperlink that doesn't open in a new tab

### ISSUE THREAD

**Issue by blah911** [uno-isqa-8950/fitgirl-inc#585]
More Arts & Crafts Ideas page

**Comment by miskelley** [comment]
This is on the Fact page but probably happening across all pages with external links.

**Comment by miskelley** [comment]
Users have been asking Wagtail for these functionality for 3 years to no avail.

Workarounds...
Option 1: Messes with embed tags
https://stackoverflow.com/questions/33300941/making-external-links-open-in-a-new-window-in-wagtail

Option 2: Makes this behavior consistent with all links that contain "http:" whether internal or external.
https://stackoverflow.com/questions/50042134/how-to-force-external-urls-inserted-in-the-wagtail-draftail-editor-to-open-on-th

**Comment by shamrose** [comment]
@miskelley says this is a Wagtail issue, there is a fix using JQuery will try doing this

**Comment by bvanscoy678** [comment]
@shamrose is going to work on this issue.

**Comment by bvanscoy678** [comment]
Checked More Arts and Craft Page. Works
