### ISSUE TITLE
As a user, I want to recieve an email if I have not logged in after 1 week of registration

### ISSUE THREAD

**Issue by bvanscoy678** [uno-isqa-8950/fitgirl-inc#588]
Login Notification - If not logged in within 1 week of registering

**Comment by bvanscoy678** [comment]
@shamrose . How many points do you want for this tasks?

**Comment by shamrose** [comment]
Brent, Please assign 8 points for this task.

Thanks.

On Mon, Mar 4, 2019 at 10:11 AM Brent Van Scoy <notifications@github.com>
wrote:

> @shamrose
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_shamrose&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=P-dTN0soHkA2ipfN7I-A1mQYLKJ59BnQ2vLk8s5_BYQ&m=LaF4fjtrN0rT06-BxltSHplx2AAxHsAwGiiLi_QRv0g&s=-KcLwVNWmG8_gpWzAemDeceQ6ufWkQQgLpqDb5Nn3vc&e=>
> . How many points do you want for this tasks?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uno-2Disqa-2D8950_fitgirl-2Dinc_issues_588-23issuecomment-2D469311062&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=P-dTN0soHkA2ipfN7I-A1mQYLKJ59BnQ2vLk8s5_BYQ&m=LaF4fjtrN0rT06-BxltSHplx2AAxHsAwGiiLi_QRv0g&s=7vYsjcmMFx7V6AjnueMoQT0BxMbFZjxQ6qSWt18yMwk&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Ad0JFNBxREOmEV3xnWrpkA7fdNr69vGLks5vTUWvgaJpZM4a6EuZ&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=P-dTN0soHkA2ipfN7I-A1mQYLKJ59BnQ2vLk8s5_BYQ&m=LaF4fjtrN0rT06-BxltSHplx2AAxHsAwGiiLi_QRv0g&s=EvMZvTRthBjKoBHy2GvWcxUznJfziw6B6isCRNimzPU&e=>
> .
>


-- 
Sincerely,
Shamrose Makandar,
Graduate Assistant-Management Information Systems,
College of Information Science & Technology,
The University of Nebraska at Omaha,
Email: smakandar@unomaha.edu
Mobile: (737)202-5219
