### ISSUE TITLE
Research - Photo Gallery - Plugin 

### ISSUE THREAD

**Issue by bvanscoy678** [uno-isqa-8950/fitgirl-inc#683]

**Comment by shamrose** [comment]
@karthikBellaryVijaya suggests to try doing this from Wagtail

**Comment by aishwaryamsd** [comment]
Research more on Simple Gallery (user side)

**Comment by bvanscoy678** [comment]
Research is completed and the plugin has been installed in test environment. Additional stories will be created for the actual galleries.
