### ISSUE TITLE
As an admin, when sending an email to a group or individual, I'd like to be able to select from a list of email templates

### ISSUE THREAD

**Issue by jlofshultuno** [uno-isqa-8950/fitgirl-inc#701]
When sending an email, the form currently offers the admin a choice to enter a message body or use a template. This request is to allow the administrator to set up multiple email templates and choose from a list when sending.

**Comment by blah911** [comment]
return button on email confirmation page is oddly placed and should be moved

**Comment by bvanscoy678** [comment]
This issue was completed, but Dr. P made more suggestions. We will create a new card for those suggestions.
