### ISSUE TITLE
Arrow on some return buttons is inconsistent

### ISSUE THREAD

**Issue by jlofshultuno** [uno-isqa-8950/fitgirl-inc#702]
Noted during Sprint 2 demo

**Comment by bvanscoy678** [comment]
This is close to the tasks I am looking at to make sure all the buttons are consistent. It might be a duplicate, but I'll leave this for now.

**Comment by bvanscoy678** [comment]
We have the buttons on every page, but in the mobile environment, the button needs to shrink as to not block the text. @karthikBellaryVijaya mentioned we will make the "Text" go away, but the arrow will stay. This issue will be placed back into the backlog.

**Comment by bvanscoy678** [comment]
The return button now shows on all pages at the top, but there are issues in the mobile environment.

**Comment by jlofshultuno** [comment]
This includes the issue with the return button showing up on top of the images on mobile devices

**Comment by bvanscoy678** [comment]
The buttons are now all consistent, but they still are not "collapsing" in the mobile environment. Still working on it.

**Comment by bvanscoy678** [comment]
@srishtynayak  completed Tasks #881 to fix in the mobile environment.

**Comment by bvanscoy678** [comment]
We still have issues with the return button covering the title of the page.
