### ISSUE TITLE
Add a nutrition game

### ISSUE THREAD

**Issue by miskelley** [uno-isqa-8950/fitgirl-inc#741]
Embed a nutrition game to the site.

**Comment by bvanscoy678** [comment]
The game does not load on an iPad. I get a blank, black screen. Failed testing.

**Comment by bvanscoy678** [comment]
After testing, @karthikBellaryVijaya  reports there is an issue with the app on the developer's site and does not work on an iPad on the main site. The app will need to be removed from the Fitgirl site as it is not working correctly.

**Comment by cecelia0128** [comment]
DRT
