### ISSUE TITLE
Return button blocking page title on mobile

### ISSUE THREAD

**Issue by miskelley** [uno-isqa-8950/fitgirl-inc#748]
This is happening on Physical and Nutritional pages. Tested on Samsung Galaxy S9.

![image.png](https://images.zenhubusercontent.com/5c36a493fdd1bf63fa7e173a/281dba28-a4c9-4201-b4ab-de33819b67f5)

![image.png](https://images.zenhubusercontent.com/5c36a493fdd1bf63fa7e173a/195a19aa-3256-4f37-8945-12e775508803)

**Comment by bvanscoy678** [comment]
@miskelley . I am working on back buttons today and @karthikBellaryVijaya is going to help me solve this issue. When the site is in a mobile environment, the text will disappear and shrink the button.

**Comment by jlofshultuno** [comment]
Duplicate issue
