### ISSUE TITLE
Add favicon.ico to site 

### ISSUE THREAD

**Issue by jlofshultuno** [uno-isqa-8950/fitgirl-inc#898]
One is created. Where should it be put in the project to have Django show it?

**Comment by Tarun1226** [comment]
@jlofshultuno I added it and it's on prod now!

**Comment by Tarun1226** [comment]
![image](https://user-images.githubusercontent.com/33792060/55689763-1f5cb000-594e-11e9-91eb-a4dc1808048d.png)
